steer_bot_hardware_gazebo:
  rear_wheel  : 'rear_wheel_joint'
  front_steer : 'front_steer_joint'
  virtual_rear_wheels  : ['rear_right_wheel_joint', 'rear_left_wheel_joint']
  virtual_front_wheels : ['front_right_wheel_joint', 'front_left_wheel_joint']
  virtual_front_steers : ['right_stear_joint', 'left_stear_joint']

  # ackermann link mechanism
  enable_ackermann_link: true
  wheel_separation_w : 0.5
  wheel_separation_h : 0.79


gains:
  base_to_right_rear_wheel  :  {p: 100000.0, d: 10.0, i: 0.50, i_clamp: 3.0}
  base_to_left_rear_wheel   :  {p: 100000.0, d: 10.0, i: 0.50, i_clamp: 3.0}
